#pragma config(Sensor, dgtl2,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  ,               sensorQuadEncoder)
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop, encoderPort, None)
#pragma config(Motor,  port2,           leftDrive1,    tmotorServoContinuousRotation, openLoop, reversed, encoderPort, None)
#pragma config(Motor,  port3,           leftDrive2,    tmotorServoContinuousRotation, PIDControl, reversed, encoderPort, dgtl4)
#pragma config(Motor,  port4,           rightDrive1,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           rightDrive2,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           shoulderR1,    tmotorServoContinuousRotation, openLoop, encoderPort, None)
#pragma config(Motor,  port7,           shoulderR2,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           shoulderL1,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           shoulderL2,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//this is a test comment

void drive(){
	motor[rightDrive1] = vexRT[Ch2];
	motor[rightDrive2] = vexRT[Ch2];
	motor[leftDrive1] = vexRT[Ch4];
	motor[leftDrive2] = vexRT[Ch4];
}

void liftShoulder(){
	if(vexRT[Btn7D]==1){
		motor[shoulderR1] = 40;
		motor[shoulderL1] = 40;
		motor[shoulderR2] = 40;
		motor[shoulderL2] = 40;
	} else if (vexRT[Btn7L] == 1){
		motor[shoulderR1] = -40;
		motor[shoulderL1] = -40;
		motor[shoulderR2] = -40;
		motor[shoulderL2] = -40;
	} else{
		motor[shoulderR1] = 0;
		motor[shoulderL1] = 0;
		motor[shoulderR2] = 0;
		motor[shoulderL2] = 0;
	}
}

void liftClaw() {
	if (vexRT[Btn7U] == 1) {
		motor[claw] = 100;
	} else if (vexRT[Btn7R] == 1) {
		motor[claw] = -100;
	} else {
		motor[claw] = 0;
	}
}

void liftGoal() {
	if (vexRT[Btn8U] == 1) {
		motor[lift] = 40;
	} else if (vexRT[Btn8R] == 1){
		motor[lift] = -40;
	} else{
		motor[lift] = 0;
	}
}

task main(){
	while(true){
		drive();
		liftShoulder();
		liftClaw();
		liftGoal();
	}
}
