#pragma config(Sensor, dgtl2,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  ,               sensorQuadEncoder)
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop, encoderPort, None)
#pragma config(Motor,  port2,           shoulderR,     tmotorServoContinuousRotation, openLoop, encoderPort, dgtl3)
#pragma config(Motor,  port3,           shoulderL,     tmotorServoContinuousRotation, openLoop, encoderPort, dgtl4)
#pragma config(Motor,  port4,           elbowR,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           elbowL,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           rightDrive,    tmotorServoContinuousRotation, PIDControl, encoderPort, dgtl1)
#pragma config(Motor,  port7,           leftDrive,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port8,           liftR,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           liftL,         tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//this is a test comment
task main(){
	while(true){
		drive();
		liftShoulder()
		liftElbows()
		liftClaw()
		liftGoal()
	}
}

void drive(){
	motor[right] = vexRT[Ch2];
	motor[left] = vexRT[Ch4];
}

void liftShoulder(){
	if(vexRT[Btn7D]==1){
		motor[shoulderR] = 40;
		motor[shoulderL] = 40;
	} else if (vexRT[Btn7L] == 1]){
		motor[shoulderR] = -40;
		motor[shoulderL] = -40;
	} else{
		motor[shoulderR] = 0;
		motor[shoulderL] = 0;
	}
}

void liftElbows() {
	if (vexRT[Btn8D] == 1) {
		motor[elbowR] = 40;
		motor[elbowL] = 40;
	} else if (vexRT[Btn7L] == 1]){
		motor[elbowR] = -40;
		motor[elbowL] = -40;
	} else{
		motor[elbowR] = 0;
		motor[elbowL] = 0;
	}
}

void liftClaw() {
	if (vexRT[Btn7U] == 1) {
		motor[claw] = 40;
	} else if (vexRT[BTN7R] == 1) {
		motor[claw] = -40;
	} else {
		motor[claw] = 0;
}

void liftGoal() {
	if (vexRT[Btn8U] == 1) {
		motor[liftR] = 40;
		motor[liftL] = 40;
	} else if (vexRT[Btn8R] == 1]){
		motor[liftR] = -40;
		motor[liftL] = -40;
	} else{
		motor[liftR] = 0;
		motor[liftL] = 0;
	}
}
